from graphic import *
r=float(input("Enter radius of circle:"))
l=float(input("Enter length of rectangle:"))
b=float(input("Enter breadth of rectangle:"))
lc=float(input("Enter length of cuboid:"))
bc=float(input("Enter breadth of cuboid:"))
hc=float(input("Enter height of cuboid:"))
rs=float(input("Enter radius of sphere:"))
print("Area of circle:",circlearea(r))
print("Perimeter of circle:",circleperimeter(r))
print("Area of rectangle:",rectanglearea(l,b))
print("Perimeter of rectangle:",rectangleperimeter(l,b))
print("Area of cuboid:",cuboidarea(lc,bc,hc))
print("Perimeter of cuboid:",cuboidperimeter(lc,bc,hc))
print("Area of sphere:",spherearea(rs))
